spring.application.name=biblioteca-api

spring.data.mongodb.uri=mongodb+srv://adminBiblioteca:biblioteca1226L-a@biblioteca-cluster.6xmcpwm.mongodb.net/biblioteca_db?retryWrites=true&w=majority

spring.data.mongodb.database=biblioteca_db

server.port=8080